name: coreference_resolution_api
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=2.116
  - blas-devel=3.9.0
  - brotlipy=0.7.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - cryptography=37.0.4
  - cudatoolkit=11.6.0
  - freetype=2.12.1
  - idna=3.4
  - intel-openmp=2022.1.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.12
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libtiff=4.4.0
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.2.2
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - requests=2.28.1
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tbb=2021.5.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.4.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
  - pip:
    - altair==4.2.0
    - anyio==3.6.2
    - astroid==2.12.12
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - black==22.10.0
    - blinker==1.5
    - brotli==1.0.9
    - catalogue==2.0.8
    - colorama==0.4.5
    - commonmark==0.9.1
    - configargparse==1.5.3
    - coreferee-model-en==1.0.0
    - coverage==6.5.0
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - en-core-web-lg==3.3.0
    - en-core-web-trf==3.3.0
    - entrypoints==0.4
    - executing==1.1.1
    - fastapi==0.85.1
    - filelock==3.8.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - gevent==22.10.1
    - geventhttpclient==2.0.8
    - greenlet==1.1.3.post0
    - h11==0.14.0
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - ipykernel==6.16.1
    - ipython==8.5.0
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - jupyter-client==7.4.3
    - jupyter-core==4.11.2
    - langcodes==3.3.0
    - lazy-object-proxy==1.7.1
    - locust==2.12.2
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - packaging==21.3
    - pandas==1.5.1
    - parso==0.8.3
    - pathspec==0.10.1
    - pathy==0.6.2
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.31
    - protobuf==3.20.3
    - pure-eval==0.2.2
    - pydantic==1.8.2
    - pydeck==0.8.0b4
    - pygments==2.13.0
    - pylint==2.15.4
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytest==7.1.3
    - pytest-cov==4.0.0
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.9.13
    - rich==12.6.0
    - roundrobin==0.0.4
    - semver==2.13.0
    - six==1.16.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - sniffio==1.3.0
    - spacy==3.3.1
    - spacy-alignments==0.8.6
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - spacy-transformers==1.1.7
    - srsly==2.4.5
    - stack-data==0.5.1
    - starlette==0.20.4
    - streamlit==1.13.0
    - thinc==8.0.17
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.5
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==4.20.1
    - typer==0.4.2
    - tzdata==2022.5
    - tzlocal==4.2
    - uvicorn==0.19.0
    - validators==0.20.0
    - wasabi==0.10.1
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.9.0
    - zope-event==4.5.0
    - zope-interface==5.5.0
